language: python

sudo: required
dist: xenial
cache:
  directories:
    - "$HOME/.cache/pip"

python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - black --check tests tapeworm
  - pylint tests tapeworm
  - pytest

before_deploy:
  - openssl aes-256-cbc -K $encrypted_89a54a178b1d_key -iv $encrypted_89a54a178b1d_iv -in instance.tar.enc -out instance.tar -d
  - tar xvf instance.tar

deploy:
  provider: gae
  keyfile: "instance/service-account.json"
  project: tapeworm-bot
  skip_cleanup: true
  on:
    branch: master
    tags: true